# Generated by Django 3.2.9 on 2021-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/static_images/in.jpg', null=True, upload_to='images_profile/', verbose_name='Картинка'),
        ),
    ]
