# Generated by Django 3.1.6 on 2021-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Емейл'),
        ),
    ]
