# Generated by Django 3.2.9 on 2021-11-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/static_images/in.jpg', null=True, upload_to='images_profile/', verbose_name='Картинка'),
        ),
    ]
