# Generated by Django 3.1.6 on 2021-07-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210722_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
    ]
