# Generated by Django 3.2.9 on 2021-11-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/home/pavel/Projects/e-com/static/static_images/no.png', null=True, upload_to='static_images/', verbose_name='Картинка'),
        ),
    ]
